stages:
    - builds

buildWindows:
    stage: builds
    variables:
        TAG: 1.test.3
        EXPECTED_ASSETS: cesium-desktop-1.test.3-windows-x64.exe
    tags:
        - shell
    script:
        - wget https://git.duniter.org/clients/cesium-grp/cesium/-/jobs/artifacts/v1.test.3/download?job=release-web -O cesium-v$TAG-web.zip
        - ./scripts/build.sh make win $TAG
        - pwd
        - ls arch/windows
  artifacts:
    untracked: true
    paths:
      - arch/windows
    expire_in: 60 minutes

test:
    stage: builds
    variables:
        GIT_STRATEGY: none
    tags:
        - shell
    script:
        - touch ceFichierNExistaitPasAvant
test2:
  stage: builds
  image: jencryzthers/vboxinsidedocker
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  script:
    - apt-get update
    - apt-get install -y linux-headers-generic linux-headers-4.4.0-137-generic
    - /sbin/vboxconfig
    - vboxheadless

