stages:
#  - builds

buildWindows:
  stage: builds
  variables:
    TAG: 1.test.3
  tags:
  - shell
  script:
  - wget https://git.duniter.org/clients/cesium-grp/cesium/-/jobs/artifacts/v$TAG/download?job=release-web -O cesium-v$TAG-web.zip
  - vboxmanage unregistervm duniter-release-windows --delete || true
  - ./scripts/build.sh make win $TAG
  - pwd
  - ls arch/windows
  artifacts:
    untracked: true
    paths:
    - arch/windows
    expire_in: 60 minutes
  only:
  - tags

test:
    stage: builds
    variables:
        GIT_STRATEGY: none
    tags:
        - shell
    script:
        - touch ceFichierNExistaitPasAvant
    only:
      - tags

test2:
  stage: builds
  image: jencryzthers/vboxinsidedocker
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  script:
    - apt-get update
    - apt-get install -y linux-headers-generic linux-headers-4.4.0-137-generic
    - /sbin/vboxconfig
    - vboxheadless
  only:
    - tags

