stages:
    - builds

buildWindows:
    stage: builds
    variables:
        TAG: 1.test.1
        EXPECTED_ASSETS: cesium-desktop-1.test.1-windows-x64.exe
    tags:
        - shell
    script:
        - ./release.sh 1.test.1

test:
    stage: builds
    variables:
        GIT_STRATEGY: none
    tags:
        - shell
    script:
        - touch ceFichierNExistaitPasAvant
test2:
  stage: builds
  image: jencryzthers/vboxinsidedocker
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  script:
    - apt-get update
    - apt-get install -y linux-headers-generic linux-headers-4.4.0-137-generic
    - /sbin/vboxconfig
    - vboxheadless

